# ./src/agent/agent.py

import json
from .llm import LLMClient
from tools import ToolRouter, ToolData
from config import SYSTEM_CONTENT
from .common_data_types import Messages


class ToolAgent:
    """
    Intelligent agent that integrates a Large Language Model (LLM) with
    external tools.

    The agent maintains a conversation history and can:
        1. Track user and assistant messages in an ordered context.
        2. Detect instructions from the LLM to call external tools.
        3. Execute the requested tool and inject the result back into
           the conversation.
        4. Provide the final assistant response incorporating tool results.

    Attributes:
        messages (Messages): Ordered history of messages exchanged.
        llm (LLMClient): Client for sending messages to the LLM.
        tools (ToolRouter): Extracts tool instructions from LLM output
                            and executes the corresponding tools.

    Example:
        >>> agent = ToolAgent()
        >>> response = agent.run("What is the weather in London?")
        >>> print(response)
    """

    def __init__(self) -> None:
        """
        Initialize the ToolAgent.

        Sets up the LLM client and the tool router, and inserts the
        system prompt to define the agent's behavior and available tools.
        """
        self.messages: Messages = []
        self.llm = LLMClient()
        self.tools = ToolRouter()
        self._add_message(role="system", content=SYSTEM_CONTENT)

    def _add_message(self, role: str, content: str) -> None:
        """
        Append a message to the conversation history.

        Args:
            role (str): Role of the message sender. Must be one of:
                        'user', 'assistant', 'system', or 'tool'.
            content (str): Text content of the message.
        """
        self.messages.append({"role": role, "content": content})

    def _get_reply(self) -> str:
        """
        Send the current conversation history to the LLM and receive
        its response.

        Returns:
            str: The raw text reply generated by the LLM.
        """
        return self.llm.send(self.messages)

    def run(self, user_input: str, retry_count: int = 0) -> str:
        """
        Process user input, handle tool calls if required, and return the
        final reply.

        The method follows these steps:
            1. Adds the user input to the conversation history.
            2. Sends the updated conversation to the LLM and receives a reply.
            3. Checks if the reply includes a request to invoke a tool.
            4. If a tool is requested:
                - Calls the tool with the specified arguments.
                - For known tools like "ltr_evaluate" or "get_weather",
                  returns the tool result directly.
                - Otherwise, adds the tool output to conversation and
                  re-queries the LLM.
            5. If the LLM reply seems to require a tool but none was parsed,
               retries up to 2 times with a system hint.
            6. Appends the final assistant reply to conversation history.

        Args:
            user_input (str): The text input from the user.
            retry_count (int): Internal counter to prevent infinite retries
                               for tool invocation compliance.

        Returns:
            str: The final assistant reply, including tool outputs
                 if applicable.

        Notes:
            - Retry limit is enforced at 2 to avoid infinite loops.
            - Tool outputs are always cast to strings before inclusion.
            - In case of errors during tool execution, the error is returned
              as part of the assistant's reply.
        """
        final_reply: str = ""

        if retry_count > 2:
            final_reply = "Error: Unable to process request. Please try again."
        else:
            self._add_message("user", user_input)
            reply: str = self._get_reply()

            tool_data: ToolData = self.tools.extract_json(reply)

            if tool_data:
                tool_name = tool_data.get("tool")
                try:
                    tool_result = self.tools.call_tool(tool_data)
                    if tool_name in ("ltr_evaluate", "get_weather"):
                        final_reply = str(tool_result)
                    else:
                        self._add_message(
                            "tool",
                            json.dumps({"result": tool_result})
                        )
                        final_reply = self._get_reply()
                except Exception as e:
                    final_reply = f"[Error calling tool {tool_name}: {e}]"
            else:
                if "weather" in user_input.lower() and retry_count < 2:
                    self._add_message(
                        "system",
                        "Reminder: Output ONLY JSON for tool calls."
                    )
                    final_reply = self.run(user_input, retry_count + 1)
                else:
                    final_reply = reply

        self._add_message("assistant", final_reply)
        return final_reply
